import pandas as pd
import random
import os

FILE_PATH = "data/Test_Data.csv"

def clean_price(value):
    if pd.isna(value):
        return None
    return float(str(value).replace("₹", "").replace(",", "").strip())

# Load CSV
df = pd.read_csv(FILE_PATH)

# Seed data if empty
if df.empty:
    print("CSV empty — seeding base product")

    seed_data = [{
        "product_id": "P1001",
        "product_name": "Bluetooth Speaker",
        "category": "Electronics",
        "discounted_price": 1299.0,
        "actual_price": 1999.0,
        "discount_percentage": 35,
        "rating": None,
        "rating_count": 0,
        "about_product": "Portable Bluetooth speaker",
        "user_id": None,
        "user_name": None,
        "review_id": None,
        "review_title": None,
        "review_content": None,
        "img_link": "",
        "product_link": ""
    }]

    df = pd.DataFrame(seed_data)

# Clean existing prices (safe)
df["discounted_price"] = df["discounted_price"].apply(clean_price)
df["actual_price"] = df["actual_price"].apply(clean_price)

# Generate unique review IDs
df["review_num"] = (
    df["review_id"]
    .astype(str)
    .str.extract(r"(\d+)")[0]
    .fillna(0)
    .astype(int)
)

last_review_id = df["review_num"].max()
products = df["product_id"].unique()

num_new_rows = random.randint(10, 20)
new_rows = []

for i in range(num_new_rows):
    product_id = random.choice(products)
    product_row = df[df["product_id"] == product_id].iloc[0]

    new_rows.append({
        "product_id": product_id,
        "product_name": product_row["product_name"],
        "category": product_row["category"],
        "discounted_price": product_row["discounted_price"],
        "actual_price": product_row["actual_price"],
        "discount_percentage": product_row["discount_percentage"],
        "rating": round(random.uniform(1, 5), 1),
        "rating_count": None,
        "about_product": product_row["about_product"],
        "user_id": f"U{random.randint(10000, 99999)}",
        "user_name": f"user_{random.randint(1000, 9999)}",
        "review_id": f"R{last_review_id + i + 1}",
        "review_title": "Test Review",
        "review_content": "This is autogenerated test data",
        "img_link": product_row["img_link"],
        "product_link": product_row["product_link"]
    })

new_df = pd.DataFrame(new_rows)

# Append and recalc rating count
final_df = pd.concat([df.drop(columns=["review_num"]), new_df], ignore_index=True)
final_df["rating_count"] = final_df.groupby("product_id")["rating"].transform("count")

final_df.to_csv(FILE_PATH, index=False)

print(f"Added {num_new_rows} rows successfully.")
